const FAVICON_BASE64 =
  'AAABAAEAEBAAAAAAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP//AAD/3wAA/88AAP+fAAD/HwAA/g8AAPwHAAD4AwAA8AEA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiIiIiIiIiIhERERERERESEREREREREhERERERERESEREREREREhERERERERESEREREREREhERERERERESEREREREREhERERERERESEREREREREhERERERERESEREREREREhERERERERESIiIiIiIiIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

export async function GET() {
  const body = Buffer.from(FAVICON_BASE64, 'base64');
  return new Response(body, {
    headers: {
      'Content-Type': 'image/x-icon',
      'Cache-Control': 'public, max-age=31536000, immutable'
    }
  });
}
